- hosts: all
  tasks:
    - name: "install httpd software"
      package:
         name: "httpd"
         state: present
    - name: "copy web page to remote target"
      copy:
         src: "myweb.html"
         dest: "/var/www/html/index.html"
    - name: "start web services"
      service: 
         name: "httpd"
         state: started
         enabled: true
